import { AmazonCatalogColumnIdsEnum } from '@/enums/catalog.enums';
import { QueryKeyEnums } from '@/enums/query.enums';

export const COGS_MAXIMUM_FILE_SIZE = 10 * 1024 * 1024;

export const AMAZON_CATALOG_3P_COLUMNS = [AmazonCatalogColumnIdsEnum.INVENTORY];

export const UPLOAD_COGS_INVALIDATE_QUERIES = [
  QueryKeyEnums.CATALOG_TABLE_FETCH,
  QueryKeyEnums.FETCH_PROFITABILITY_GRAPH_DATA,
  QueryKeyEnums.FETCH_PROFITABILITY_PERFORMANCE_DATA,
  QueryKeyEnums.FETCH_PROFITABILITY_ORDERS_TABLE_DATA,
  QueryKeyEnums.FETCH_PROFITABILITY_PRODUCTS_TABLE_DATA,
  QueryKeyEnums.FETCH_PROFITABILITY_TOTAL_PRODUCTS_DATA,
  QueryKeyEnums.FETCH_PROFITABILITY_TOTAL_TABLE_DATA,
  QueryKeyEnums.FETCH_AMAZON_PROFITABILITY_ORDERS_TABLE_DATA,
  QueryKeyEnums.FETCH_AMAZON_PROFITABILITY_ORDERS_AGGREGATED_DATA,
  QueryKeyEnums.FETCH_AMAZON_PROFITABILITY_PRODUCTS_TABLE_DATA,
  QueryKeyEnums.FETCH_AMAZON_PROFITABILITY_PRODUCTS_AGGREGATED_DATA,
  QueryKeyEnums.FETCH_AMAZON_PROFITABILITY_PERFORMANCE_DATA,
  QueryKeyEnums.FETCH_AMAZON_PROFITABILITY_GRAPH_DATA,
];
