export type DecisionSeverity = 'critical' | 'opportunity' | 'fyi';
export type DecisionStatus = 'open' | 'with_aan' | 'in_flight' | 'completed' | 'rejected' | 'snoozed' | 'expired';

export interface Decision {
  id: string;
  insight: string;
  insightDetail?: string;
  severity: DecisionSeverity;
  status: DecisionStatus;
  source: string;
  sourceLabel: string;
  domain: string;
  category: string;
  valueCents: number;
  valueKind: 'revenue' | 'savings' | 'risk' | 'efficiency';
  valueCaption: string;
  valueBasis?: string;
  valueInputs?: string[];
  cadence?: string;
  actionVerb: string;
  createdAt: number;
  snoozedUntil?: number;
  meetingRef?: { bundleId: string; title: string; excerpt?: string };
  deepLink?: { href: string; label: string };
}

export const MOCK_DECISIONS: Decision[] = [
  {
    id: 'critical-b0csh8tcc6',
    insight: 'ASIN B0CSH8TCC6 lost advertising eligibility on 07 Jun',
    insightDetail: 'Amazon disabled advertising for ASIN B0CSH8TCC6 (Sampler – Decaf 40 Count) on 07 Jun 2026, citing missing or incorrect listing information. Estimated revenue at risk is $6,885 over the next 7 days.',
    severity: 'critical',
    status: 'open',
    source: 'amazon',
    sourceLabel: 'Amazon Ads',
    domain: 'Listing Compliance',
    category: 'advertising',
    valueCents: 688500,
    valueKind: 'risk',
    valueCaption: 'Revenue at risk over 7 days',
    valueBasis: 'Based on average daily ad-attributed sales of $983.57 over the past 30 days. Inventory position: 2,810 units (~140 days of coverage).',
    valueInputs: [
      'Average daily ad-attributed sales: $983.57 (30-day trailing)',
      'Estimated revenue at risk (7 days): $6,885',
      'Estimated units at risk: ~300 units',
      'Inventory available: 2,810 units (~140 days of coverage)',
      'Confidence: 82% based on historical ad performance',
    ],
    cadence: 'daily',
    actionVerb: 'Investigate & fix',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'opp-sales-dip-01',
    insight: 'ACoS spiked 23% on Sponsored Brands campaign "Brand Defense"',
    insightDetail: 'The "Brand Defense" Sponsored Brands campaign saw ACoS rise from 18% to 41% over the past 3 days. Main contributor: keyword "decaf coffee pods" saw CPC increase of $0.85.',
    severity: 'opportunity',
    status: 'open',
    source: 'amazon',
    sourceLabel: 'Amazon Ads',
    domain: 'Advertising',
    category: 'advertising',
    valueCents: 320000,
    valueKind: 'savings',
    valueCaption: 'Potential monthly savings',
    valueBasis: 'Optimizing keyword bids on underperforming terms could recover ~$3,200 monthly in ad spend.',
    cadence: 'weekly',
    actionVerb: 'Optimize bids',
    createdAt: Date.now() - 7200000,
  },
  {
    id: 'fyi-restock-01',
    insight: 'ASIN B09XYZ1234 running low — 14 days of cover left',
    insightDetail: 'ASIN B09XYZ1234 (Premium Roast 80 Count) has 14 days of inventory cover at current sales velocity. Reorder lead time is 21 days, suggesting an imminent stock-out.',
    severity: 'fyi',
    status: 'open',
    source: 'internal',
    sourceLabel: 'Inventory Tracker',
    domain: 'Supply Chain',
    category: 'inventory',
    valueCents: 1500000,
    valueKind: 'risk',
    valueCaption: 'Revenue at risk if stock-out occurs',
    valueBasis: 'This ASIN generates ~$50,000/week in revenue. A stock-out of 2 weeks would cost ~$100,000 in lost sales.',
    cadence: 'daily',
    actionVerb: 'Place reorder',
    createdAt: Date.now() - 10800000,
  },
  {
    id: 'opp-csat-01',
    insight: 'Customer satisfaction dropped 12 points for "Sampler Variety Pack"',
    insightDetail: 'CSAT for ASIN B0VARIETY01 dropped from 4.2 to 3.0 over the last week. Negative reviews cite "pod compatibility issues" and "weak brew strength".',
    severity: 'opportunity',
    status: 'open',
    source: 'internal',
    sourceLabel: 'Review Analysis',
    domain: 'Customer Experience',
    category: 'customer-service',
    valueCents: 450000,
    valueKind: 'revenue',
    valueCaption: 'Estimated monthly revenue impact',
    cadence: 'daily',
    actionVerb: 'Review & respond',
    createdAt: Date.now() - 14400000,
  },
  {
    id: 'fyi-competitor-01',
    insight: 'Competitor "BrewMaster" launched 40-count sampler at $2.99',
    insightDetail: 'BrewMaster launched a new 40-count sampler pod SKU priced at $2.99, directly undercutting our $3.99 Sampler – Decaf 40 Count. They are currently #8 in search for "decaf coffee pods".',
    severity: 'fyi',
    status: 'open',
    source: 'internal',
    sourceLabel: 'Market Intelligence',
    domain: 'Competitive Analysis',
    category: 'competitor',
    valueCents: 0,
    valueKind: 'efficiency',
    valueCaption: 'Competitive threat level: Medium',
    cadence: 'weekly',
    actionVerb: 'Monitor & adjust',
    createdAt: Date.now() - 18000000,
  },
  {
    id: 'opp-pricing-01',
    insight: 'Price gap alert: Our $3.99 vs. category average $3.12 for decaf pods',
    insightDetail: 'The category average price for decaf single-serve pods (40-count) is $3.12. Our ASIN B0CSH8TCC6 is priced at $3.99, a 28% premium. Conversion rate is 12% vs. category average of 18%.',
    severity: 'opportunity',
    status: 'open',
    source: 'internal',
    sourceLabel: 'Profitability Dashboard',
    domain: 'Pricing',
    category: 'profitability',
    valueCents: 280000,
    valueKind: 'revenue',
    valueCaption: 'Estimated uplift from price optimization',
    cadence: 'daily',
    actionVerb: 'Optimize price',
    createdAt: Date.now() - 21600000,
  },
  {
    id: 'fyi-trend-01',
    insight: '"Organic coffee pods" search volume up 34% week-over-week',
    insightDetail: 'Search volume for "organic coffee pods" increased 34% WoW. We have no organic-certified listings. This represents a potential traffic gap.',
    severity: 'fyi',
    status: 'open',
    source: 'internal',
    sourceLabel: 'Keyword Tracker',
    domain: 'Market Intelligence',
    category: 'market-changes',
    valueCents: 500000,
    valueKind: 'revenue',
    valueCaption: 'Estimated monthly opportunity',
    cadence: 'weekly',
    actionVerb: 'Explore opportunity',
    createdAt: Date.now() - 25200000,
  },
  {
    id: 'fyi-insight-01',
    insight: 'Subscribe & Save enrollment grew 18% this quarter',
    insightDetail: 'S&S enrollment across top 20 ASINs grew from 12% to 30% this quarter. Average repeat purchase rate for S&S customers is 73% vs. 24% for non-S&S.',
    severity: 'fyi',
    status: 'open',
    source: 'internal',
    sourceLabel: 'Analytics',
    domain: 'Business Insights',
    category: 'insights',
    valueCents: 0,
    valueKind: 'efficiency',
    valueCaption: 'Key business metric',
    cadence: 'monthly',
    actionVerb: 'Review report',
    createdAt: Date.now() - 28800000,
  },
  {
    id: 'critical-listing-02',
    insight: 'ASIN B0NEWASIN01 blocked for "Restricted Product" policy violation',
    insightDetail: 'Amazon blocked ASIN B0NEWASIN01 (Dark Roast 80 Count) citing a "Restricted Product" policy violation. The listing is currently suppressed and not visible to customers.',
    severity: 'critical',
    status: 'open',
    source: 'amazon',
    sourceLabel: 'Amazon Seller Central',
    domain: 'Listing Compliance',
    category: 'retail-listings',
    valueCents: 1200000,
    valueKind: 'risk',
    valueCaption: 'Monthly revenue at risk',
    cadence: 'daily',
    actionVerb: 'File appeal',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'completed-inflight-01',
    insight: 'Automated bid adjustment applied to "Brand Defense" campaign',
    insightDetail: 'Aan automatically adjusted bids on 12 keywords in the "Brand Defense" campaign. Average CPC reduced from $2.45 to $1.92 while maintaining impression share.',
    severity: 'fyi',
    status: 'completed',
    source: 'internal',
    sourceLabel: 'Aan AI',
    domain: 'Advertising',
    category: 'advertising',
    valueCents: 180000,
    valueKind: 'savings',
    valueCaption: 'Weekly ad spend savings',
    cadence: 'daily',
    actionVerb: 'Review changes',
    createdAt: Date.now() - 86400000,
  },
];