import type { PrototypeAlert } from './prototype-data';

export const EXTRA_ALERTS_B: PrototypeAlert[] = [
  {
    id: 'a56', day: 'today', time: '08:20 AM', valueNum: -3200, valueLabel: '−$3,200', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Incorrect category or browse node', impactStr: 'Reduced category discoverability', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 5 days',
    subheader: "This ASIN is classified under the wrong browse node, so it isn't surfacing in the category shoppers search.",
    why: 'The item was mapped to an incorrect browse node during catalog setup and no longer reflects the product\'s real category.',
    root: 'No catalog validation step checks browse-node assignment against the product\'s actual classification at listing creation.',
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$3,200', confidence: 74,
    source: 'Catalog Agent, browse node audit', proof: 'estimated',
    aiSummary: "Updating the item classification and browse node so the product appears in its correct category — without miscategorizing just to dodge a stricter category's policy requirements — should restore normal discoverability.",
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Herbal Detox Tea 30ct', sku: 'B0NUT5512', impact: '−$3,200', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Update the item classification and browse node so the product appears in its correct category', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$3,200', confidence: 74, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a57', day: 'today', time: '09:40 AM', valueNum: -900, valueLabel: '−$900', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Missing material, fabric or ingredient attribute', impactStr: 'Conversion at risk', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 7 days',
    subheader: 'Required ingredient/material attribute is missing on this listing, which can suppress category-specific search filters.',
    why: 'The listing went live without the material, fabric-composition, or ingredient attribute required for this product category.',
    root: "Product metadata doesn't consistently capture composition data before listings go live.",
    oppWindow: '30 days', revLabel: 'Revenue at risk', revValue: '$900', confidence: 68,
    source: 'Catalog Agent, attribute completeness scan', proof: 'estimated',
    aiSummary: 'Reviewing product metadata for a recommendation on the missing attribute (editable before submission), and filling it via a custom field when metadata has no value, closes the gap.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Whey Protein Isolate 1kg', sku: 'B0WEL3391', impact: '−$900', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Add the missing material/fabric/ingredient attribute from a metadata-based recommendation or a custom field', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$900', confidence: 68, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a58', day: 'yesterday', time: '29 Sep · 13:10', valueNum: -850, valueLabel: '−$850', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Missing item package quantity or number of items', impactStr: 'Listing flagged for data quality', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 7 days',
    subheader: "The listing doesn't declare the exact package quantity, which triggered a data-quality flag.",
    why: 'The exact number of sellable units included in one customer order was never entered on this listing.',
    root: "Package-quantity entry isn't cross-checked against title, images, and unit count during listing creation.",
    oppWindow: '30 days', revLabel: 'Revenue at risk', revValue: '$850', confidence: 66,
    source: 'Catalog Agent, attribute completeness scan', proof: 'estimated',
    aiSummary: 'Entering the exact package quantity — matched to the title, images, and unit count, sourced from metadata or a custom field when metadata has no value — resolves the flag.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Collagen Peptides Jar 3-pack', sku: 'B0BLD4477', impact: '−$850', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Enter the exact package quantity, matching the title, images and unit count', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$850', confidence: 66, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a59', day: 'today', time: '10:05 AM', valueNum: -780, valueLabel: '−$780', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Missing model number or manufacturer part number', impactStr: 'Listing flagged for data quality', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 6 days',
    subheader: 'The listing is missing its model number / manufacturer part number, required for this product type.',
    why: 'The model or manufacturer part number was never added when this listing was set up.',
    root: "There's no check that model/part numbers are captured against manufacturer documentation before publishing.",
    oppWindow: '30 days', revLabel: 'Revenue at risk', revValue: '$780', confidence: 65,
    source: 'Catalog Agent, attribute completeness scan', proof: 'estimated',
    aiSummary: 'Adding the correct model/manufacturer part number via a custom field by attribute, matched against manufacturer documentation, resolves the gap.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Adjustable Resistance Band Set', sku: 'B0NUT6620', impact: '−$780', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Add the correct model/manufacturer part number via a custom field, matching manufacturer documentation', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$780', confidence: 65, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a60', day: 'yesterday', time: '29 Sep · 15:45', valueNum: -2600, valueLabel: '−$2,600', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Missing age range, target audience or intended user', impactStr: 'Conversion at risk', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 5 days',
    subheader: 'Required age-range/intended-user attribute is missing for this category.',
    why: 'The listing was published without the age range, department, or intended-user information this category requires.',
    root: "Metadata review doesn't consistently flag missing audience/age-range fields before go-live.",
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$2,600', confidence: 70,
    source: 'Catalog Agent, attribute completeness scan', proof: 'estimated',
    aiSummary: 'Reviewing metadata for a recommendation on the missing attribute (editable), with a custom field fallback when metadata has no value, fills the gap.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Kids Multivitamin Gummies', sku: 'B0WEL7734', impact: '−$2,600', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Add the missing age range/target audience attribute from a metadata-based recommendation or a custom field', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$2,600', confidence: 70, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a61', day: 'today', time: '07:50 AM', valueNum: -7400, valueLabel: '−$7,400', priority: 'High', priorityDot: '#b3453f',
    title: 'Listing suppressed: image shows incorrect pack count or package size', impactStr: 'Listing suppressed, no sales', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: "The listing is suppressed because the pack count shown in the image doesn't match the listing attributes.",
    why: "The pack count/package size shown in the product image doesn't line up with what's declared in the attributes.",
    root: "Images and package-size attributes aren't reconciled before a listing goes live.",
    oppWindow: '14 days', revLabel: 'Revenue at risk', revValue: '$7,400', confidence: 80,
    source: 'Catalog Agent, suppression scan', proof: 'estimated',
    aiSummary: 'Checking which is correct — the attribute or the image — and updating whichever is wrong (the attribute if the image is right, the image if the attribute is right) should lift the suppression.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Omega-3 Fish Oil 60 Softgels', sku: 'B0BLD8812', impact: '−$7,400', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Reconcile the pack count between the image and the attribute, and correct whichever is wrong', desc: 'Matches recommended action: Update product images.', expected: '+$7,400', confidence: 80, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a62', day: 'yesterday', time: '28 Sep · 16:30', valueNum: -8100, valueLabel: '−$8,100', priority: 'High', priorityDot: '#b3453f',
    title: 'Listing suppressed: image contains offensive or unsafe content', impactStr: 'Listing suppressed, no sales', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The listing is suppressed after a product image was flagged as offensive or unsafe.',
    why: 'One of the listing images contains content flagged as offensive, explicit, or otherwise unsafe.',
    root: "Image review before submission doesn't check adult-product and category-specific image policies.",
    oppWindow: '14 days', revLabel: 'Revenue at risk', revValue: '$8,100', confidence: 83,
    source: 'Catalog Agent, suppression scan', proof: 'estimated',
    aiSummary: 'Removing the non-compliant image, replacing it with appropriate product imagery, and reviewing adult-product and category-specific image policies before resubmitting should lift the suppression.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Herbal Sleep Support Capsules', sku: 'B0NUT9013', impact: '−$8,100', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Remove the non-compliant image and replace it with policy-appropriate product imagery', desc: 'Matches recommended action: Update product images.', expected: '+$8,100', confidence: 83, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a63', day: 'today', time: '08:05 AM', valueNum: -9200, valueLabel: '−$9,200', priority: 'High', priorityDot: '#b3453f',
    title: 'Product policy violation: prohibited medical or disease-treatment claims', impactStr: 'Listing at risk of removal', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Compliance', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: "This listing makes a disease-treatment claim that Amazon hasn't authorized for this product.",
    why: 'The listing claims the product diagnoses, cures, treats, prevents, or mitigates a disease, which is not legally authorized or permitted by Amazon for this product.',
    root: "Claims language isn't checked against product-claim policy before publishing.",
    oppWindow: '14 days', revLabel: 'Revenue at risk', revValue: '$9,200', confidence: 85,
    source: 'Compliance Agent, policy violation scan', proof: 'estimated',
    aiSummary: 'Finding the root cause, removing the unsupported claim, and — once corrected — raising a ticket/appeal with supporting documentation is the path back to compliance.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Joint Support Formula 60ct', sku: 'B0WEL1123', impact: '−$9,200', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-policy-violation',
    options: [
      { id: 'o1', kind: 'PROCESS', label: 'Remove the unsupported disease-treatment claim and raise a policy appeal with supporting documentation', desc: 'Matches recommended action: Resolve product policy/compliance violation.', expected: '+$9,200', confidence: 85, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a64', day: 'yesterday', time: '29 Sep · 10:20', valueNum: -3800, valueLabel: '−$3,800', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Product policy violation: unsupported organic or eco-friendly claim', impactStr: 'Listing at risk of removal', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Compliance', repeated: false, hasMeeting: false, windowLabel: 'Act within 5 days',
    subheader: 'This listing carries an organic/eco-friendly claim without documentation on file.',
    why: 'The listing has an unsupported organic, biodegradable, non-toxic, cruelty-free, clinically-tested, or certification claim in its attributes or images, without valid documentation.',
    root: "Claims aren't matched against certification documents before publishing.",
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$3,800', confidence: 76,
    source: 'Compliance Agent, policy violation scan', proof: 'estimated',
    aiSummary: 'Finding the root cause, then removing the unsupported claim or providing valid documentation, and raising a ticket/appeal with supporting attachments should resolve it.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Organic Ashwagandha Powder 200g', sku: 'B0BLD2256', impact: '−$3,800', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-policy-violation',
    options: [
      { id: 'o1', kind: 'PROCESS', label: 'Remove the unsupported organic/eco claim or attach valid certification, and raise a policy appeal', desc: 'Matches recommended action: Resolve product policy/compliance violation.', expected: '+$3,800', confidence: 76, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a65', day: 'today', time: '09:30 AM', valueNum: -6500, valueLabel: '−$6,500', priority: 'High', priorityDot: '#b3453f',
    title: "Product policy violation: missing or expired children's product safety documentation", impactStr: 'Listing at risk of removal', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Compliance', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: "Required children's-product safety documentation is missing or expired for this ASIN.",
    why: "The listing is missing the required children's product certificate, lab testing report, or product/packaging images matching this exact ASIN.",
    root: "Certification renewal and documentation matching isn't tracked per ASIN.",
    oppWindow: '14 days', revLabel: 'Revenue at risk', revValue: '$6,500', confidence: 84,
    source: 'Compliance Agent, policy violation scan', proof: 'estimated',
    aiSummary: 'Finding the root cause and submitting the required certificate, lab report, and matching product/packaging images via a ticket/appeal with attachments resolves the flag.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Kids Calcium Gummies 60ct', sku: 'B0NUT3348', impact: '−$6,500', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-policy-violation',
    options: [
      { id: 'o1', kind: 'PROCESS', label: "Submit the required children's product certificate, lab report and matching images via a policy appeal", desc: 'Matches recommended action: Resolve product policy/compliance violation.', expected: '+$6,500', confidence: 84, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a66', day: 'yesterday', time: '28 Sep · 11:55', valueNum: -7800, valueLabel: '−$7,800', priority: 'High', priorityDot: '#b3453f',
    title: 'Product policy violation: button cell / battery compliance information missing', impactStr: 'Listing at risk of removal', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Compliance', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'Required battery compliance information is missing for this battery-containing product.',
    why: 'The listing is missing required battery type, battery count, warning information, test documentation, or product/packaging images for this battery-containing product.',
    root: "Battery-compliance documentation isn't collected before battery-containing listings go live.",
    oppWindow: '14 days', revLabel: 'Revenue at risk', revValue: '$7,800', confidence: 82,
    source: 'Compliance Agent, policy violation scan', proof: 'estimated',
    aiSummary: 'Finding the root cause and submitting the required battery type, count, warnings, test documentation, and images via a ticket/appeal resolves the flag.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Digital Kitchen Scale (Button Cell)', sku: 'B0WEL5567', impact: '−$7,800', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-policy-violation',
    options: [
      { id: 'o1', kind: 'PROCESS', label: 'Submit the required battery compliance documentation via a policy appeal', desc: 'Matches recommended action: Resolve product policy/compliance violation.', expected: '+$7,800', confidence: 82, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a67', day: 'today', time: '10:45 AM', valueNum: -4100, valueLabel: '−$4,100', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Product policy violation: pesticide claim without required registration', impactStr: 'Listing at risk of removal', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Compliance', repeated: false, hasMeeting: false, windowLabel: 'Act within 5 days',
    subheader: 'This listing makes a pesticide/pest-control claim without registration information on file.',
    why: 'The listing makes a pesticide or pest-control claim, which may be regulated, without the applicable registration/compliance information on file.',
    root: "Regulated-claim language isn't checked against registration status before publishing.",
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$4,100', confidence: 75,
    source: 'Compliance Agent, policy violation scan', proof: 'estimated',
    aiSummary: 'Finding the root cause, then removing the claim or providing the required registration via a ticket/appeal resolves it.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Neem Oil Insect Repellent Spray', sku: 'B0BLD6689', impact: '−$4,100', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-policy-violation',
    options: [
      { id: 'o1', kind: 'PROCESS', label: 'Remove the pesticide claim or provide the required registration via a policy appeal', desc: 'Matches recommended action: Resolve product policy/compliance violation.', expected: '+$4,100', confidence: 75, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a68', day: 'yesterday', time: '29 Sep · 14:15', valueNum: -8600, valueLabel: '−$8,600', priority: 'High', priorityDot: '#b3453f',
    title: 'Product policy violation: adult or explicit product content', impactStr: 'Listing at risk of removal', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Compliance', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'This listing contains prohibited explicit content and may be ineligible to list.',
    why: 'The listing contains prohibited explicit imagery or language; some adult products may not be eligible for listing at all.',
    root: "Explicit-content and category-eligibility checks aren't run before submission.",
    oppWindow: '14 days', revLabel: 'Revenue at risk', revValue: '$8,600', confidence: 86,
    source: 'Compliance Agent, policy violation scan', proof: 'estimated',
    aiSummary: 'Finding the root cause, removing the prohibited content, and raising a ticket/appeal if the product itself is contested as ineligible is the path forward.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Intimate Wellness Massage Oil', sku: 'B0NUT4471', impact: '−$8,600', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-policy-violation',
    options: [
      { id: 'o1', kind: 'PROCESS', label: 'Remove the prohibited explicit content and raise a policy appeal if eligibility is contested', desc: 'Matches recommended action: Resolve product policy/compliance violation.', expected: '+$8,600', confidence: 86, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a69', day: 'today', time: '08:50 AM', valueNum: -6000, valueLabel: '−$6,000', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Content change on the listing dragged performance down', impactStr: 'Revenue declining week-over-week', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 5 days',
    subheader: 'Performance dropped in the week after a title/image/bullet-point change on these listings.',
    why: "A change went live on the listing's title, image, or bullet points, and performance dropped over the following week.",
    root: "Listing changes aren't checked against before/after performance before being left in place.",
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$6,000', confidence: 78,
    source: 'Analytics Agent, performance trend', proof: 'estimated',
    aiSummary: 'Checking what changed on the listing in the last 30 days and comparing CTR, CVR, sessions and page views for the 7 days before and after the change should isolate the cause.',
    itemsCount: 2, itemsBreakdown: '2 ASINs', itemsBadge: '2 ASINs',
    items: [
      { name: 'Vitamin D3 Gummies 90ct', sku: 'B0WEL8834', impact: '−$3,400', color: '#b3453f' },
      { name: 'Ashwagandha Capsules 60ct', sku: 'B0WEL8835', impact: '−$2,600', color: '#b3453f' },
    ],
    mappedActionTypeId: 'investigate-sales-decline',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Compare CTR, CVR, sessions and page views for 7 days before/after the listing change to isolate the cause', desc: 'Matches recommended action: Investigate sales/performance decline root cause.', expected: '+$6,000', confidence: 78, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a70', day: 'yesterday', time: '28 Sep · 09:25', valueNum: -4500, valueLabel: '−$4,500', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Price moved 5%+ versus the 30-day average', impactStr: 'Margin/conversion at risk', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Profitability', repeated: false, hasMeeting: false, windowLabel: 'Act within 4 days',
    subheader: 'Current price has moved more than 5% versus its 30-day average base price.',
    why: 'The current price moved more than 5% versus the 30-day average base price, and if the move was an increase, sales could fall roughly 10% if left uncorrected.',
    root: "Price changes aren't checked against the 30-day average before going live.",
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$4,500', confidence: 77,
    source: 'Pricing Agent, price monitoring', proof: 'estimated',
    aiSummary: 'Checking sales over the last 30 days, estimating the roughly 10% sales reduction if a price increase isn\'t corrected, and confirming whether the change was intentional or erroneous resolves it.',
    itemsCount: 1, itemsBreakdown: '1 ASIN', itemsBadge: '1 ASIN',
    items: [{ name: 'Boldfit Shaker Bottle 700ml', sku: 'B0BLD9901', impact: '−$4,500', color: '#b3453f' }],
    mappedActionTypeId: 'fix-pricing-error',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Check the 30-day sales trend and confirm whether the 5%+ price increase was intentional or erroneous', desc: 'Matches recommended action: Fix pricing error/margin correction.', expected: '+$4,500', confidence: 77, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
];
