import type { PrototypeAlert } from './prototype-data';

export const EXTRA_ALERTS_A: PrototypeAlert[] = [
  {
    id: 'a37', day: 'yesterday', time: '12 Sep · 16:40', valueNum: -1800, valueLabel: '−$1,800', priority: 'High', priorityDot: '#b3453f',
    title: 'Warehouse damaged inventory: reimbursement not yet issued', impactStr: 'Reimbursement pending', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Inventory', repeated: false, hasMeeting: false, windowLabel: 'Act within 7 days',
    subheader: 'A unit was marked warehouse-damaged and the reimbursement case hasn’t been confirmed.',
    why: 'The unit was marked warehouse-damaged during a routine inventory check, but the corresponding reimbursement adjustment hasn’t posted to the ledger.',
    root: 'Damage write-offs aren’t automatically cross-checked against the reimbursement queue, so eligible claims can sit unresolved.',
    oppWindow: '30 days', revLabel: 'Revenue at risk', revValue: '$1,800', confidence: 78,
    source: 'Inventory Agent, damage reimbursement report', proof: 'estimated',
    aiSummary: 'Confirming reimbursement eligibility and raising a case for the missing adjustment recovers the value of the damaged unit; if it isn’t eligible, returning to seller or disposing of the unit closes it out.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Whey Protein Isolate 2kg · Chocolate', sku: 'B0912DMG31', impact: '−$1,800', color: '#b3453f' }],
    mappedActionTypeId: 'resolve-inventory-reimbursement-claim',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Confirm reimbursement eligibility and raise a case for the missing adjustment', desc: 'Matches recommended action: File warehouse loss/damage reimbursement claim.', expected: '+$1,800', confidence: 78, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a38', day: 'today', time: '07:10 AM', valueNum: -1200, valueLabel: '−$1,200', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Removal order stuck pending beyond the normal window', impactStr: 'Removal stalled', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Inventory', repeated: false, hasMeeting: false, windowLabel: 'Act within 5 days',
    subheader: 'A removal order has stayed in pending status well past the normal processing window.',
    why: 'The removal order was created 18 days ago and remains pending, with no tracking information generated yet.',
    root: 'Removal orders past the typical processing window aren’t flagged for manual follow-up until a support case is raised.',
    oppWindow: '18 days', revLabel: 'Revenue at risk', revValue: '$1,200', confidence: 74,
    source: 'Inventory Agent, removal order log', proof: 'estimated',
    aiSummary: 'Checking the order’s creation date, status, destination and unit count, then raising a support case, unblocks the stuck removal and recovers the units.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Omega-3 Fish Oil 60ct', sku: 'B07RMV0512', impact: '−$1,200', color: '#b3453f' }],
    mappedActionTypeId: 'escalate-fba-shipment',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Check the removal order details and raise a support case', desc: 'Matches recommended action: Escalate FBA shipment/receiving issue.', expected: '+$1,200', confidence: 74, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a39', day: 'yesterday', time: '11 Sep · 11:05', valueNum: -950, valueLabel: '−$950', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Removal order cancelled: units still need to move', impactStr: 'Units not moving', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Inventory', repeated: false, hasMeeting: false, windowLabel: 'Act within 7 days',
    subheader: 'A removal order was cancelled before the units could be shipped back or disposed of.',
    why: 'The removal order was cancelled due to an address problem flagged during processing.',
    root: 'Cancelled removal orders aren’t automatically resubmitted once the underlying issue is fixed, leaving units stranded.',
    oppWindow: '21 days', revLabel: 'Revenue at risk', revValue: '$950', confidence: 71,
    source: 'Inventory Agent, removal order log', proof: 'estimated',
    aiSummary: 'Correcting the flagged address/inventory issue and creating a new removal order for the remaining eligible quantity gets the units moving again.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Resistance Bands Set Medium', sku: 'B0CNCL2039', impact: '−$950', color: '#b3453f' }],
    mappedActionTypeId: 'investigate-inventory-misallocation',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Fix the cancellation issue and create a new removal order', desc: 'Matches recommended action: Investigate inventory misallocation/bin check.', expected: '+$950', confidence: 71, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a40', day: 'today', time: '08:20 AM', valueNum: -4800, valueLabel: '−$4,800', priority: 'High', priorityDot: '#b3453f',
    title: 'Aged inventory approaching long-term storage charges', impactStr: 'Long-term storage risk', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Inventory', repeated: false, hasMeeting: false, windowLabel: 'Act within 10 days',
    subheader: 'Several SKUs are aging past the 120-day mark, heading toward long-term storage charges at 180 days.',
    why: 'Sell-through has slowed on these SKUs while they continue to sit in the 120-day aging bucket, approaching the 180-day long-term storage threshold.',
    root: 'Aging inventory isn’t reviewed against sell-through velocity until it crosses into long-term storage charge territory.',
    oppWindow: '45 days', revLabel: 'Revenue at risk', revValue: '$4,800', confidence: 82,
    source: 'Inventory Agent, inventory age report', proof: 'estimated',
    aiSummary: 'For the SKUs unlikely to sell profitably, creating a removal or liquidation order now avoids long-term storage charges; for the rest, advertising, a coupon/promotion, or routing through MCF to another marketplace can move them before writing them off.',
    itemsCount: 4, itemsBreakdown: '4 SKUs', itemsBadge: '4 SKUs',
    items: [
      { name: 'Multivitamin Gummies 90ct', sku: 'B08AGE1123', impact: '−$1,500', color: '#b3453f' },
      { name: 'Creatine Monohydrate 300g', sku: 'B08AGE2245', impact: '−$1,300', color: '#b3453f' },
      { name: 'Collagen Peptides 500g', sku: 'B08AGE3367', impact: '−$1,100', color: '#b3453f' },
      { name: 'Green Tea Extract 60ct', sku: 'B08AGE4489', impact: '−$900', color: '#b3453f' },
    ],
    mappedActionTypeId: 'liquidation-excess-inventory',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Create a removal or liquidation order for the SKUs unlikely to sell profitably', desc: 'Matches recommended action: Liquidation/excess inventory management.', expected: '+$4,800', confidence: 82, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a41', day: 'today', time: '09:05 AM', valueNum: -700, valueLabel: '−$700', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: missing size or color attribute', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The listing is suppressed because a required Size or Color attribute value is missing.',
    why: 'The catalog feed left the Size or Color attribute blank, and the listing is suppressed from search until it’s filled in.',
    root: 'The listing template doesn’t enforce Size/Color as a required field before publishing.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$700', confidence: 88,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Updating the listing with the correct size or color attribute value and saving reactivates it in search within 30 minutes to an hour.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Yoga Mat 6mm · Purple', sku: 'B0SZC0R781', impact: '−$700', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Update the missing Size or Color attribute and save', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$700', confidence: 88, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a42', day: 'yesterday', time: '13 Sep · 13:15', valueNum: -650, valueLabel: '−$650', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: missing product identifier (UPC/GTIN/EAN)', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The listing is suppressed for a missing UPC/GTIN/EAN product identifier.',
    why: 'The product identifier field was left blank on submission, triggering an automatic search suppression.',
    root: 'Products without a barcode on file are published without falling back to a GENERIC identifier designation.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$650', confidence: 85,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Adding the correct UPC/GTIN/EAN — or selecting the GENERIC checkbox if the listing genuinely has none — clears the suppression.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Push Up Bars Pro', sku: 'B0UPC00456', impact: '−$650', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Add the correct product identifier, or mark GENERIC if none exists', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$650', confidence: 85, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a43', day: 'today', time: '06:50 AM', valueNum: -400, valueLabel: '−$400', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: missing unit count or unit value', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'A consumable-category listing is missing its required unit count or unit value attribute.',
    why: 'This category requires a unit count/unit value attribute that wasn’t populated from the product metadata during submission.',
    root: 'The metadata pipeline doesn’t always carry a unit-count field for consumable SKUs, and there’s no fallback to a custom input.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$400', confidence: 80,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Filling in the unit count/unit value — from metadata, or via a custom input field if metadata doesn’t have it — clears the suppression.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Electrolyte Powder Sachets 20ct', sku: 'B0UNIT0789', impact: '−$400', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Fill in the missing unit count/unit value attribute', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$400', confidence: 80, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a44', day: 'yesterday', time: '09 Sep · 15:30', valueNum: -900, valueLabel: '−$900', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: main image shows a mannequin', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The main image shows the product displayed on a mannequin, which this category doesn’t allow.',
    why: 'The main image was shot on a mannequin form instead of a plain product shot or an approved live-model shot.',
    root: 'The photography brief for this category wasn’t updated to exclude mannequin shots.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$900', confidence: 86,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Replacing the main image with a plain product shot (or a compliant live-model shot, per category rules), saving, and waiting 30 minutes to an hour reactivates the listing.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Compression Sleeve Set', sku: 'B0MANQ1102', impact: '−$900', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Replace the main image with a plain product shot', desc: 'Matches recommended action: Update product images.', expected: '+$900', confidence: 86, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a45', day: 'today', time: '10:40 AM', valueNum: -1100, valueLabel: '−$1,100', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed due to a parent ASIN issue', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'The child ASIN is suppressed because of an unresolved issue on its parent ASIN.',
    why: 'The parent ASIN carries a flagged attribute or image issue, and every child under it is suppressed until that’s fixed.',
    root: 'Parent-level listing issues aren’t monitored separately from child-level ones, so a parent problem goes unnoticed.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$1,100', confidence: 75,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Identifying the parent ASIN and fixing the flagged attribute or image issue on it reinstates every suppressed child automatically; a support ticket is only needed if it’s still unresolved after 24 hours.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Adjustable Dumbbell Set 20kg', sku: 'B0PRNT2234', impact: '−$1,100', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Identify and fix the flagged issue on the parent ASIN', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$1,100', confidence: 75, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a46', day: 'yesterday', time: '14 Sep · 09:50', valueNum: -800, valueLabel: '−$800', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: text, logo or watermark on main image', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The main image contains text, a logo, or a watermark, which isn’t permitted.',
    why: 'The main image includes a promotional watermark that was left in during the last image refresh.',
    root: 'The image-upload checklist doesn’t flag watermarks or overlay text before publishing.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$800', confidence: 87,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Editing the image to remove all text/logo/watermark so only the product is visible, uploading it, saving, and waiting 30 minutes to an hour clears the suppression.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Protein Shaker Bottle 700ml', sku: 'B0WTRM0567', impact: '−$800', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Remove the text/logo/watermark from the main image and re-upload', desc: 'Matches recommended action: Update product images.', expected: '+$800', confidence: 87, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a47', day: 'today', time: '07:55 AM', valueNum: -750, valueLabel: '−$750', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: main image background isn’t pure white', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The main image background isn’t pure white, as this category requires.',
    why: 'The main image was shot against an off-white studio backdrop rather than pure white (RGB 255,255,255).',
    root: 'The photo studio’s default backdrop isn’t calibrated to pure white for every shoot.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$750', confidence: 84,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Replacing the main image with one on a pure white background, saving, and waiting 30 minutes to an hour reactivates the listing; a support ticket is only needed if it’s still suppressed after that.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Vitamin D3 Drops 30ml', sku: 'B0WHIT0912', impact: '−$750', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Replace the main image with one on a pure white background', desc: 'Matches recommended action: Update product images.', expected: '+$750', confidence: 84, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a48', day: 'yesterday', time: '10 Sep · 17:20', valueNum: -500, valueLabel: '−$500', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: main image has prohibited badging', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'The main image includes a badge, award, or certification mark, which isn’t permitted.',
    why: 'The main image carries a certification badge overlay that was added for marketing purposes.',
    root: 'Marketing-provided images aren’t screened for badge overlays before they’re used as the main image.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$500', confidence: 83,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Removing the badge/award/certification mark, uploading a clean compliant image, saving, and waiting 30 minutes to an hour clears the suppression.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Foam Roller 33cm', sku: 'B0BADG0345', impact: '−$500', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Remove the badge/certification mark from the main image', desc: 'Matches recommended action: Update product images.', expected: '+$500', confidence: 83, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a49', day: 'today', time: '08:35 AM', valueNum: -600, valueLabel: '−$600', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: main image model isn’t standing', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'The main image shows the model in a seated pose, which this product type’s image requirements don’t allow.',
    why: 'This product type’s image requirements call for the model to be shown standing, but the current shot has them seated.',
    root: 'The photography brief wasn’t cross-checked against this product type’s specific pose requirement.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$600', confidence: 81,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Updating the main image so the model is shown standing, saving, and waiting 30 minutes to an hour reinstates the listing.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Athletic Leggings High-Waist', sku: 'B0STND0678', impact: '−$600', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Update the main image so the model is shown standing', desc: 'Matches recommended action: Update product images.', expected: '+$600', confidence: 81, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a50', day: 'yesterday', time: '08 Sep · 12:10', valueNum: -700, valueLabel: '−$700', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: human model not permitted for this product', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The main image shows a human model, but this non-clothing product type doesn’t permit one.',
    why: 'The main image was shot with a hand model holding the product, which isn’t allowed for this product type.',
    root: 'The image guidelines for non-clothing categories weren’t checked before the human-model shot was used.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$700', confidence: 85,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Replacing the image with a plain product shot with no human model, saving, and waiting 30 minutes to an hour reactivates the listing.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Digital Kitchen Scale', sku: 'B0HMOD0789', impact: '−$700', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Replace the main image with a plain product shot, no human model', desc: 'Matches recommended action: Update product images.', expected: '+$700', confidence: 85, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a51', day: 'today', time: '09:45 AM', valueNum: -450, valueLabel: '−$450', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: missing Department attribute', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'The listing is missing its required Department attribute.',
    why: 'The Department attribute (Men/Women/Unisex/Kids) was never set when the listing was created.',
    root: 'The listing template doesn’t mark Department as a required field for this category.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$450', confidence: 82,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Updating the Department attribute as applicable, saving, and waiting 30 minutes to an hour reactivates the listing; a support ticket is only needed if it’s still not active.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Training Gloves Unisex M', sku: 'B0DEPT0234', impact: '−$450', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Update the Department attribute and save', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$450', confidence: 82, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a52', day: 'yesterday', time: '15 Sep · 14:05', valueNum: -550, valueLabel: '−$550', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: non-compliant markup in an attribute', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'A listing attribute contains HTML or JavaScript markup, which isn’t permitted.',
    why: 'The item description was pasted in from a template that carried over HTML tags instead of plain text.',
    root: 'The copy pipeline doesn’t strip markup before it’s submitted to the attribute field.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$550', confidence: 80,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Editing the flagged attribute to strip all markup, keeping plain text only, saving, and waiting 30 minutes to an hour reactivates the listing; a support ticket is only needed if it’s still not active.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Herbal Detox Tea 30 Bags', sku: 'B0MRKP0456', impact: '−$550', color: '#b3453f' }],
    mappedActionTypeId: 'update-listing-copy',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Strip the markup from the flagged attribute and save', desc: 'Matches recommended action: Update listing copy (title/bullets/description).', expected: '+$550', confidence: 80, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a53', day: 'today', time: '11:15 AM', valueNum: -650, valueLabel: '−$650', priority: 'Medium', priorityDot: '#5c7f9e',
    title: 'Search suppressed: product too small in the main image frame', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Wellbeing Nutrition', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 2 days',
    subheader: 'The product occupies too little of the main image frame.',
    why: 'The main image was shot from too far back, leaving the product occupying a small fraction of the frame.',
    root: 'The photography guideline for frame-fill percentage wasn’t enforced during the last image refresh.',
    oppWindow: '2 days', revLabel: 'Revenue at risk', revValue: '$650', confidence: 83,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Retaking the main image so the product fills roughly 70% of the frame while staying fully visible, uploading it, saving, and waiting 30 minutes to an hour reactivates the listing; a support ticket is only needed if it’s still not active.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Massage Gun Mini', sku: 'B0FRME0567', impact: '−$650', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Retake the main image so the product fills ~70% of the frame', desc: 'Matches recommended action: Update product images.', expected: '+$650', confidence: 83, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a54', day: 'yesterday', time: '07 Sep · 10:20', valueNum: -500, valueLabel: '−$500', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: missing Brand attribute', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Boldfit', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'The listing is missing its Brand attribute.',
    why: 'The Brand field was left blank when the listing was created, triggering the suppression.',
    root: 'The listing template doesn’t require Brand before allowing submission.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$500', confidence: 84,
    source: 'Catalog Agent, listing quality report', proof: 'estimated',
    aiSummary: 'Updating the Brand attribute field with the correct brand name — or listing under GENERIC if unregistered — and saving reactivates the listing within 30 minutes to an hour.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Ankle Weights 2kg Pair', sku: 'B0BRND0678', impact: '−$500', color: '#b3453f' }],
    mappedActionTypeId: 'fix-listing-data',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Update the Brand attribute, or mark GENERIC if unregistered', desc: 'Matches recommended action: Fix listing data/attributes (backend fields).', expected: '+$500', confidence: 84, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
  {
    id: 'a55', day: 'today', time: '06:30 AM', valueNum: -600, valueLabel: '−$600', priority: 'Low', priorityDot: '#3f7d6a',
    title: 'Search suppressed: prohibited props in main image', impactStr: 'Listing suppressed', mpBrand: 'amazon', mpColor: '#e78a2e', mpCountry: 'US',
    account: 'Nutrabay', category: 'Catalog', repeated: false, hasMeeting: false, windowLabel: 'Act within 3 days',
    subheader: 'The main image includes props placed in, on, or around the product, which isn’t permitted.',
    why: 'The main image was styled with decorative props around the product for a lifestyle look.',
    root: 'The image styling guidelines for the main image slot weren’t distinguished from secondary/lifestyle image slots.',
    oppWindow: '3 days', revLabel: 'Revenue at risk', revValue: '$600', confidence: 82,
    source: 'Catalog Agent, image compliance report', proof: 'estimated',
    aiSummary: 'Removing any props from the main image, uploading a compliant image, saving, and waiting 30 minutes to an hour reactivates the listing; a support ticket is only needed if it’s still not active.',
    itemsCount: 1, itemsBreakdown: '1 SKU', itemsBadge: '1 SKU',
    items: [{ name: 'Jump Rope Speed Cable', sku: 'B0PROP0789', impact: '−$600', color: '#b3453f' }],
    mappedActionTypeId: 'update-product-images',
    options: [
      { id: 'o1', kind: 'INSTRUCTIVE', label: 'Remove the props from the main image and re-upload', desc: 'Matches recommended action: Update product images.', expected: '+$600', confidence: 82, recommended: true },
      { id: 'other', kind: 'OTHER', label: 'Do something else', desc: 'Write your own action.', isOther: true },
    ],
  },
];
