export enum PageTitleEnum {
  ADVERTISING = 'Advertising',
  CATALOG_HOME = 'Catalog',
  IMPACT_ANALYSIS = 'Impact Analysis',
  TARGETING_ACTIONS = 'Targeting Actions',
  QUERIES = 'Queries',
  EXECUTED_QUERIES = 'Executed Queries',
  SCHEDULES = 'Schedules',
  AUDIENCES = 'Audiences',
  CREATED_AUDIENCES = 'Created Audiences',
  INSTANCES = 'Instances',
  BRAND_SOV = 'Brand SOV',
  KEYWORD_SOV = 'Keyword SOV',
  PRODUCT_SOV = 'Product SOV',
  KEYWORD_TRACKER = 'Keyword Tracker',
  DAY_PARTING = 'Day Parting',
  JOB_LIST = 'Job List',
  HISTORY = 'History',
  SCHEDULED_JOBS = 'Scheduled Jobs',
  ACCOUNTS = 'Accounts',
  LOGS = 'Logs',
  INVITES = 'Invites',
  USERS = 'Users',
  REPORTS = 'Reports',
  MONITORING = 'Monitoring',
  AMC = 'Amazon Marketing Cloud',
  ONBOARDING = 'Onboarding',
  BRAND_ANALYTICS = 'Brand Analytics',
  PROFITABILITY_DASHBOARD = 'Profit Dashboard',
  PROFITABILITY_TRENDS = 'Trends',
  PROFITABILITY_PROFIT_N_LOSS = 'Profit & Loss',
  MONITORING_HISTORY = 'Monitoring History',
  MONITORING_CRON_DEFINITIONS = 'Cron Configurations',
  QUEUES_INFO = 'Queues Info',
  BIDDER_DASHBOARD = 'Bidder Dashboard',
  RULES_AGENTS = 'Rule Agents',
  RULES_CREATION = 'Rule Creation',
  APPLIED_RULES = 'Applied Rules',
  CONFIGURATION_WIZARD = 'Configuration Wizard',
}

export enum DropdownLabelEnum {
  MARKETPLACE = 'Marketplace',
  SPONSORED_ACCOUNT = 'Sponsored Account',
  DSP_ACCOUNT = 'DSP Account',
  CATALOG_ACCOUNT = 'Catalog',
  AD_TYPE = 'Ad Type',
  REGION = 'Region',
  DATE_RANGE = 'Date Range',
  INSTANCE = 'Instance',
  ACCOUNT = 'Account',
}

export enum EnvironmentEnum {
  DEVELOPMENT = 'development',
  DEV = 'dev',
  TEST = 'test',
  PROD = 'production',
}

export enum BackendServiceNameEnum {
  Advertising = 'advertising',
  MarketIntelligence = 'market-intelligence',
  AmazonScrapper = 'amazon-scrapper',
  Auth = 'auth',
  TargetSov = 'target-sov',
  Dayparting = 'dayparting',
  AMC = 'amc',
  Bidder = 'bidder',
  WalmartBidder = 'walmart-bidder',
  AIBidder = 'ai-bidder',
  PriceTracker = 'price-tracker',
  Monitoring = 'monitoring',
  AmazonAds = 'amazon-ads',
  WalmartAds = 'walmart-ads',
  DbSync = 'db-sync',
  TargetingAction = 'targeting-action',
  JIVA_LLM = 'jiva-llm',
  CronWorker = 'cron-worker',
  TaskProcessor = 'task-processor',
  Integrations = 'integrations',
  DlqProcessor = 'dlq-processor',
  D2C = 'd2c',
  All = 'all',
}

export enum VersionEnum {
  V1 = 'v1',
  V2 = 'v2',
}

export enum MetricInputTypeEnum {
  NUMBER = 'number',
  DROPDOWN = 'dropdown',
}
