import { TRuleValueType } from '@/interfaces/rules/rules.interfaces';
import {
  MetricsKeysEnum,
  PageTypeActualEnum,
  PlacementBids,
} from './advertising.enums';
import { FeaturesEnum } from './auth.enums';
import { FilterDropdownValue } from './filter.enums';

export enum RuleTypeEnum {
  INVENTORY_RULE = 'INVENTORY_RULE',
  PLATFORM_RULE = 'PLATFORM_RULE',
  SOV_RULE = 'SOV_RULE',
  STATE_CHANGE_RULE = 'STATE_CHANGE_RULE',
  BUDGET_RULE = 'BUDGET_RULE',
  BIDDING_STRATEGY_RULE = 'BIDDING_STRATEGY_RULE',
  KEYWORD_RULE = 'KEYWORD_RULE',
  TARGET_RULE = 'TARGET_RULE',
  BIDDER_RULE = 'BIDDER_RULE',
  UNKNOWN = 'UNKNOWN',
  KEYWORD_HARVESTING_RULE = 'KEYWORD_HARVESTING_RULE',
  PLACEMENT_RULE = 'PLACEMENT_RULE',
  PAGE_TYPE_RULE = 'PAGE_TYPE_RULE',
  DAYPARTING_RULE = 'DAYPARTING_RULE',
}

export enum RuleStatusEnum {
  ENABLED = 'ENABLED',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
  DRAFT = 'DRAFT',
  ENDED = 'ENDED',
}

export enum RuleExecutionModeEnum {
  APPLY_CHANGES = 'APPLY_CHANGES',
  PREVIEW_ONLY = 'PREVIEW_ONLY',
}

export enum RuleEntityTypeIdEnum {
  CAMPAIGN_ID = 'CAMPAIGN_ID',
  ADGROUP_ID = 'ADGROUP_ID',
  ASIN = 'ASIN',
  KEYWORD_ID = 'KEYWORD_ID',
  TARGET_ID = 'TARGET_ID',
  AD_ITEM_ID = 'AD_ITEM_ID',
  ITEM_ID = 'ITEM_ID',
  SOURCE_TARGET_MAPPING_ID = 'SOURCE_TARGET_MAPPING_ID',
  PLACEMENT_CAMPAIGN_ID = 'PLACEMENT_CAMPAIGN_ID',
  PLATFORM_CAMPAIGN_ID = 'PLATFORM_CAMPAIGN_ID',
}

export enum AmazonRuleOperatorEnum {
  GREATER_THAN_EQUAL_TO = 'GREATER_THAN_EQUAL_TO',
  LESS_THAN_EQUAL_TO = 'LESS_THAN_EQUAL_TO',
  GREATER_THAN = 'GREATER_THAN',
  LESS_THAN = 'LESS_THAN',
  EQUAL_TO = 'EQUAL_TO',
}

export enum RuleValueTypeEnum {
  ABSOLUTE = 'ABSOLUTE',
  CALCULATED = 'CALCULATED',
  DERIVED = 'DERIVED',
}

export enum RuleActionTypeEnum {
  PAUSE = 'PAUSE',
  ENABLE = 'ENABLE',
  SET_BID_ABSOLUTE = 'SET_BID_ABSOLUTE',
  INCREASE_BID = 'INCREASE_BID',
  DECREASE_BID = 'DECREASE_BID',
  INCREASE_BUDGET = 'INCREASE_BUDGET',
  DECREASE_BUDGET = 'DECREASE_BUDGET',

  // Amazon Budget Actions
  INCREASE_BUDGET_PERCENTAGE = 'INCREASE_BUDGET_PERCENTAGE',
  DECREASE_BUDGET_PERCENTAGE = 'DECREASE_BUDGET_PERCENTAGE',
  INCREASE_BUDGET_VALUE = 'INCREASE_BUDGET_VALUE',
  DECREASE_BUDGET_VALUE = 'DECREASE_BUDGET_VALUE',
  HOLD_BUDGET = 'HOLD_BUDGET',

  // Walmart Budget Actions - Daily Budget
  INCREASE_DAILY_BUDGET_PERCENTAGE = 'INCREASE_DAILY_BUDGET_PERCENTAGE',
  DECREASE_DAILY_BUDGET_PERCENTAGE = 'DECREASE_DAILY_BUDGET_PERCENTAGE',
  INCREASE_DAILY_BUDGET_VALUE = 'INCREASE_DAILY_BUDGET_VALUE',
  DECREASE_DAILY_BUDGET_VALUE = 'DECREASE_DAILY_BUDGET_VALUE',
  HOLD_DAILY_BUDGET = 'HOLD_DAILY_BUDGET',

  // Walmart Budget Actions - Total Budget
  INCREASE_TOTAL_BUDGET_PERCENTAGE = 'INCREASE_TOTAL_BUDGET_PERCENTAGE',
  DECREASE_TOTAL_BUDGET_PERCENTAGE = 'DECREASE_TOTAL_BUDGET_PERCENTAGE',
  INCREASE_TOTAL_BUDGET_VALUE = 'INCREASE_TOTAL_BUDGET_VALUE',
  DECREASE_TOTAL_BUDGET_VALUE = 'DECREASE_TOTAL_BUDGET_VALUE',
  HOLD_TOTAL_BUDGET = 'HOLD_TOTAL_BUDGET',
  KEYWORD_HARVESTING = 'KEYWORD_HARVESTING',
  SET_BIDDING_STRATEGY_DOWN_ONLY = 'SET_BIDDING_STRATEGY_DOWN_ONLY',
  SET_BIDDING_STRATEGY_UP_DOWN = 'SET_BIDDING_STRATEGY_UP_DOWN',
  SET_BIDDING_STRATEGY_FIXED = 'SET_BIDDING_STRATEGY_FIXED',
  SET_BIDDING_STRATEGY_RULE_BASED = 'SET_BIDDING_STRATEGY_RULE_BASED',
  PLACEMENT_ADJUSTMENT = 'PLACEMENT_ADJUSTMENT',
  PLATFORM_ADJUSTMENT = 'PLATFORM_ADJUSTMENT',
  INCREASE_BY_VALUE = 'INCREASE_BY_VALUE',
  DECREASE_BY_VALUE = 'DECREASE_BY_VALUE',
  SET_TO_VALUE = 'SET_TO_VALUE',
  INCREASE_BY_PERCENTAGE = 'INCREASE_BY_PERCENTAGE',
  DECREASE_BY_PERCENTAGE = 'DECREASE_BY_PERCENTAGE',
}

export enum RuleTypeCategoryEnum {
  CAMPAIGN_RULE = 'campaignRule',
  TARGETING_RULE = 'targetingRule',
}

export enum RuleTypeCategoryNameEnum {
  CAMPAIGN_RULE = 'Campaign Rules',
  TARGETING_RULE = 'Targeting Rules',
}

export enum RuleCreationLookbackEnum {
  DAYS_7 = 7,
  DAYS_14 = 14,
  DAYS_30 = 30,
  DAYS_60 = 60,
}

export enum MetricsAbbrEnum {
  // Percent metrics
  ACOS = 'ACOS',
  CTR = 'CTR',
  CVR = 'CVR',
  TACOS = 'TACO',
  PERCENTAGE_ORDERS_NTB = 'NTBO',
  PERCENTAGE_SALES_NTB = 'NTBS',
  PERCENTAGE_UNITS_NTB = 'NTBU',
  CVR_UNITS = 'CVRU',
  CVR_ORDERS = 'CVRO',
  VIDEO_5_SECOND_VIEW_RATE = 'V5R',
  VTR = 'VTR',
  VCTR = 'VCTR',
  LQS = 'LQS',
  PRODUCT_SOV = 'SOV',
  GROSS_MARGIN_PERCENTAGE = 'GMP',
  BID_MULTIPLIER = 'MULT',

  // Currency metrics ($)
  AD_SPEND = 'SPND',
  AD_SALES = 'ASLS',
  ROAS = 'ROAS',
  CPC = 'CPC',
  CUSTOM_BID = 'CBID',
  BID = 'BID',
  TOTAL_SALES = 'TSLS',
  ADVERTISED_SKU_SALES = 'ASKU',
  OTHER_SKU_SALES = 'OSKU',
  NTB_SALES = 'NTBS',
  VCPM = 'VCPM',
  GMV = 'GMV',
  DEFAULT_BID = 'DBID',
  BUDGET = 'BDGT',
  TOTAL_BUDGET = 'TBGT',
  DAILY_BUDGET = 'DBGT',
  MIN_BID = 'MINB',
  MAX_BID = 'MAXB',
  TROAS = 'TROA',
  ASIN_PRICE = 'PRCE',
  VIEW_THROUGH_AD_SALES = 'VTAS',
  COMPLETE_VIEW_AD_SALES = 'CVAS',
  OTHER_COMPLETE_VIEW_AD_SALES = 'OCVS',
  REVENUE_COST = 'RCST',
  INVENTORY_VALUE = 'IVLU',
  INVENTORY_VALUE_COGS = 'ICOG',
  INVENTORY_VALUE_RETAIL = 'IRET',
  PRICE = 'PRCE',
  COGS = 'COGS',
  WALMART_FEE = 'FEE',
  GROSS_MARGIN = 'GMAR',
  CANCELLED_SALES_PRICE = 'CNSL',
  REFUND_SALES = 'RFSL',
  GROSS_SALES = 'GSLS',
  PROMO_SPEND = 'PRSP',
  IN_STORE_ATTRIBUTES_SALES = 'ISAS',
  IN_STORE_ADVERTISED_SALES = 'ISAD',
  IN_STORE_OTHER_SALES = 'ISOS',
  OMNI_CHANNEL_SALES = 'OMSL',
  OMNI_CHANNEL_ROAS = 'OMRA',
  LISTING_PRICE = 'LPRC',
  GMV_COMMISSION = 'GMVC',

  // Count / numeric metrics
  IMPRESSIONS = 'IMPR',
  CLICKS = 'CLKS',
  AD_UNITS = 'AUNT',
  TOTAL_UNITS = 'TUNT',
  AD_ORDERS = 'AORD',
  ADVERTISED_SKU_UNITS = 'ASUN',
  OTHER_SKU_UNITS = 'OSUN',
  NTB_UNITS = 'NTBU',
  NTB_ORDERS = 'NTBO',
  ORDERS = 'ORDR',
  VIEWABLE_IMPRESSIONS = 'VIMP',
  COMPLETE_VIEW_AD_ORDERS = 'CVO',
  VIDEO_5_SECOND_VIEWS = 'V5V',
  UNITS_SOLD = 'USLD',
  ADGROUP_COUNT = 'ADGP',
  RATINGS = 'RTNG',
  REVIEWS = 'RVWS',
  COMPLETE_VIEW_ORDERS = 'CVOR',
  COMPLETE_VIEW_AD_UNITS = 'CVUN',
  VIDEO_COMPLETE_VIEWS = 'VCV',
  VIDEO_FIRST_QUARTILE_VIEWS = 'V1QV',
  VIDEO_IMPRESSIONS = 'VIMP',
  VIDEO_MIDPOINT_VIEWS = 'VMID',
  VIDEO_THIRD_QUARTILE_VIEWS = 'V3QV',
  VIDEO_UNMUTES = 'VUNM',
  VIEW_THROUGH_AD_ORDERS = 'VTOR',
  VIEW_THROUGH_AD_UNITS = 'VTUN',
  INVENTORY = 'INVT',
  AVAIL_TO_SELL_QUANTITY = 'ATSQ',
  RETURNS = 'RETN',
  CANCELLED_ORDERS = 'CNOR',
  REFUND_ORDERS = 'RFOR',
  GROSS_UNITS_SOLD = 'GUNT',
  AD_UNITS_SOLD = 'AUSL',
  CAMPAIGNS = 'CMPN',
  IN_STORE_UNITS_SOLD = 'ISUN',
  IN_STORE_ORDERS = 'ISOR',
  INPUT_QUANTITY = 'INQT',
  CVR_UNIT_SOLD_BASED = 'CVRU',
  CVR_ORDER_BASED = 'CVRO',
  SUGGESTED_DAILY_BUDGET_COLUMN = 'SDBGT',
  SUGGESTED_TOTAL_BUDGET_COLUMN = 'STBGT',

  PRODUCT_AD = 'PRDNM',
  BIDDER_MAX_BID = 'MXBID',
  BIDDER_MIN_BID = 'MNBID',
  BIDDER_TROAS = 'TROAS',
  BIDDER_STATUS = 'BSTAT',
  COST = 'COST',
  AVG_CLICKS = 'ACLKS',
  AVG_CVR = 'ACVR',
  CVR_MEDIAN = 'MCVR',
  THIRTY_PERCENT_OF_TROAS = '30TRS',
  THIRTY_FIVE_PERCENT_OF_ASP = '35ASP',
  FBA_INVENTORY = 'FBAI',
  WFS_INVENTORY = 'WFSI',
  DAYS_OF_SUPPLY = 'DOS',
  WEEKS_OF_SUPPLY = 'WOS',
  ESTIMATED_EXCESS_QUANTITY = 'EEQ',
  TOTAL_ORDERS = 'TORD',
  TOTAL_ACOS = 'TACOS',
  NET_PROFIT = 'NPRO',
  INV_AGE_0_90 = 'A090',
  INV_AGE_91_180 = 'A180',
  INV_AGE_181_270 = 'A270',
  INV_AGE_271_365 = 'A365',
  INV_AGE_365_PLUS = 'A365P',
  TOTAL_AGED_INVENTORY = 'TAI',

  CAMPAIGN_BUDGET = 'CBUDG',
  OUT_OF_BUDGET = 'OOBUD',
  DAYS_SINCE_CAMPAIGN_START = 'DSCS',
  AVG_SPEND = 'AVSPD',
  CPA = 'CPA',
  TACOS_TARGET = 'TACOS',
  OOB_PERCENTAGE = 'OOBP',
  OUT_OF_BUDGET_HOUR = 'OOBHR',

  TOS_IMPRESSIONS = 'TOSIM',
  TOS_CLICKS = 'TOSCL',
  TOS_UNITS_SOLD = 'TOSUS',
  TOS_CPC = 'TCPC',
  TOS_CVR = 'TCVR',
  TOS_CTR = 'TCTR',
  TOS_SALES = 'TSALE',
  TOS_SPEND = 'TSPND',
  TOS_ACOS = 'TACOS',
  TOS_ROAS = 'TROAS',

  ROS_IMPRESSIONS = 'ROSIM',
  ROS_CLICKS = 'ROSCL',
  ROS_UNITS_SOLD = 'ROSUS',
  ROS_CPC = 'RCPC',
  ROS_CVR = 'RCVR',
  ROS_CTR = 'RCTR',
  ROS_SALES = 'RSALE',
  ROS_SPEND = 'RSPND',
  ROS_ACOS = 'RACOS',
  ROS_ROAS = 'RROAS',

  PRODUCT_PAGE_IMPRESSIONS = 'PPIMP',
  PRODUCT_PAGE_CLICKS = 'PPCLK',
  PRODUCT_PAGE_UNITS_SOLD = 'PPUSD',
  PRODUCT_PAGE_CPC = 'PPCPC',
  PRODUCT_PAGE_CVR = 'PPCVR',
  PRODUCT_PAGE_CTR = 'PPCTR',
  PRODUCT_PAGE_SALES = 'PPSAL',
  PRODUCT_PAGE_SPEND = 'PSPND',
  PRODUCT_PAGE_ACOS = 'PACOS',
  PRODUCT_PAGE_ROAS = 'PROAS',

  BUY_BOX_IMPRESSIONS = 'BBIMP',
  BUY_BOX_CLICKS = 'BBCLK',
  BUY_BOX_UNITS_SOLD = 'BBUSD',
  BUY_BOX_CPC = 'BBCPC',
  BUY_BOX_CVR = 'BBCVR',
  BUY_BOX_CTR = 'BBCTR',
  BUY_BOX_SALES = 'BBSAL',
  BUY_BOX_SPEND = 'BSPND',
  BUY_BOX_ACOS = 'BACOS',
  BUY_BOX_ROAS = 'BROAS',

  SEARCH_INGRID_IMPRESSIONS = 'SIIMP',
  SEARCH_INGRID_CLICKS = 'SICLK',
  SEARCH_INGRID_UNITS_SOLD = 'SIUSD',
  SEARCH_INGRID_CPC = 'SICPC',
  SEARCH_INGRID_CVR = 'SICVR',
  SEARCH_INGRID_CTR = 'SICTR',
  SEARCH_INGRID_SALES = 'SISAL',
  SEARCH_INGRID_SPEND = 'SSPND',
  SEARCH_INGRID_ACOS = 'SACOS',
  SEARCH_INGRID_ROAS = 'SROAS',

  HOME_PAGE_IMPRESSIONS = 'HPIMP',
  HOME_PAGE_CLICKS = 'HPCLK',
  HOME_PAGE_UNITS_SOLD = 'HPUSD',
  HOME_PAGE_CPC = 'HPCPC',
  HOME_PAGE_CVR = 'HPCVR',
  HOME_PAGE_CTR = 'HPCTR',
  HOME_PAGE_SALES = 'HPSAL',
  HOME_PAGE_SPEND = 'HSPND',
  HOME_PAGE_ACOS = 'HACOS',
  HOME_PAGE_ROAS = 'HROAS',

  STOCK_UP_IMPRESSIONS = 'SUIMP',
  STOCK_UP_CLICKS = 'SUCLK',
  STOCK_UP_UNITS_SOLD = 'SUUSD',
  STOCK_UP_CPC = 'SUCPC',
  STOCK_UP_CVR = 'SUCVR',
  STOCK_UP_CTR = 'SUCTR',
  STOCK_UP_SALES = 'SUSAL',
  STOCK_UP_SPEND = 'SSUPD',
  STOCK_UP_ACOS = 'SUACS',
  STOCK_UP_ROAS = 'SUROS',

  STATISTICALLY_SIGNIFICANT_CLICKS = 'SSCLK',
  SELLER_FULFILLED_INVENTORY = 'SFINV',
}

export enum MetricsTitleEnum {
  ACOS = 'ACOS',
  CTR = 'CTR',
  CVR = 'CVR',
  TACOS = 'TACOS',
  PERCENTAGE_ORDERS_NTB = 'Percentage Orders NTB',
  PERCENTAGE_SALES_NTB = 'Percentage Sales NTB',
  PERCENTAGE_UNITS_NTB = 'Percentage Units NTB',
  CVR_UNITS = 'CVR Units',
  CVR_ORDERS = 'CVR Orders',
  VIDEO_5_SECOND_VIEW_RATE = 'Video 5 Second View Rate',
  PERCENT_NTB_UNITS = 'Percent NTB Units',
  PERCENT_NTB_ORDERS = 'Percent NTB Orders',
  PERCENT_NTB_SALES = 'Percent NTB Sales',
  BID_MULTIPLIER = 'Bid Multiplier',
  VTR = 'VTR',
  VCTR = 'VCTR',
  VIDEO_5_SEC_VIEW_RATE = 'Video 5 Sec View Rate',
  LQS = 'LQS',
  PRODUCT_SOV = 'Product SOV',
  GROSS_MARGIN_PERCENTAGE = 'Gross Margin Percentage',
  CVR_UNIT_SOLD_BASED = 'CVR Unit Sold Based',
  CVR_ORDER_BASED = 'CVR Order Based',

  AD_SPEND = 'Ad Spend',
  AD_SALES = 'Ad Sales',
  ROAS = 'ROAS',
  CPC = 'CPC',
  CUSTOM_BID = 'Custom Bid',
  BID = 'Bid',
  TOTAL_SALES = 'Total Sales',
  ADVERTISED_SKU_SALES = 'Advertised SKU Sales',
  OTHER_SKU_SALES = 'Other SKU Sales',
  NTB_SALES = 'NTB Sales',
  VCPM = 'VCPM',
  GMV = 'GMV',
  DEFAULT_BID = 'Default Bid',
  BUDGET = 'Budget',
  ADVERTISED_SALES = 'Advertised Sales',
  OTHER_SALES = 'Other Sales',
  TOTAL_BUDGET = 'Total Budget',
  DAILY_BUDGET = 'Daily Budget',
  BID_WALMART = 'Bid Walmart',
  MIN_BID = 'Min Bid',
  MAX_BID = 'Max Bid',
  TROAS = 'TROAS',
  ASIN_PRICE = 'ASIN Price',
  VIEW_THROUGH_AD_SALES = 'View Through Ad Sales',
  COMPLETE_VIEW_AD_SALES = 'Complete View Ad Sales',
  OTHER_COMPLETE_VIEW_AD_SALES = 'Other Complete View Ad Sales',
  REVENUE_COST = 'Revenue Cost',
  INVENTORY_VALUE = 'Inventory Value',
  INVENTORY_VALUE_COGS = 'Inventory Value COGS',
  INVENTORY_VALUE_RETAIL = 'Inventory Value Retail',
  PRICE = 'Price',
  COGS = 'COGS',
  WALMART_FEE = 'Walmart Fee',
  GROSS_MARGIN = 'Gross Margin',
  CANCELLED_SALES_PRICE = 'Cancelled Sales Price',
  REFUND_SALES = 'Refund Sales',
  GROSS_SALES = 'Gross Sales',
  PROMO_SPEND = 'Promo Spend',
  SUGGESTED_DAILY_BUDGET_COLUMN = 'Suggested Daily Budget',
  SUGGESTED_TOTAL_BUDGET_COLUMN = 'Suggested Total Budget',
  IN_STORE_ATTRIBUTES_SALES = 'In Store Attributed Sales',
  IN_STORE_ADVERTISED_SALES = 'In Store Advertised Sales',
  IN_STORE_OTHER_SALES = 'In Store Other Sales',
  OMNI_CHANNEL_SALES = 'Omni Channel Sales',
  OMNI_CHANNEL_ROAS = 'Omni Channel ROAS',
  LISTING_PRICE = 'Listing Price',
  GMV_COMMISSION = 'GMV Commission',

  IMPRESSIONS = 'Impressions',
  CLICKS = 'Clicks',
  AD_UNITS = 'Ad Units',
  TOTAL_UNITS = 'Total Units',
  AD_ORDERS = 'Ad Orders',
  ADVERTISED_SKU_UNITS = 'Advertised SKU Units',
  OTHER_SKU_UNITS = 'Other SKU Units',
  NTB_UNITS = 'NTB Units',
  NTB_ORDERS = 'NTB Orders',
  ORDERS = 'Orders',
  VIEWABLE_IMPRESSIONS = 'Viewable Impressions',
  COMPLETE_VIEW_AD_ORDERS = 'Complete View Ad Orders',
  VIDEO_5_SECOND_VIEWS = 'Video 5 Second Views',
  UNITS_SOLD = 'Units Sold',
  ADVERTISED_UNITS = 'Advertised Units',
  OTHER_UNITS = 'Other Units',
  ADGROUP_COUNT = 'Ad Group Count',
  RATINGS = 'Ratings',
  REVIEWS = 'Reviews',
  COMPLETE_VIEW_ORDERS = 'Complete View Orders',
  COMPLETE_VIEW_AD_UNITS = 'Complete View Ad Units',
  VIDEO_COMPLETE_VIEWS = 'Video Complete Views',
  VIDEO_FIRST_QUARTILE_VIEWS = 'Video First Quartile Views',
  VIDEO_IMPRESSIONS = 'Video Impressions',
  VIDEO_MIDPOINT_VIEWS = 'Video Midpoint Views',
  VIDEO_THIRD_QUARTILE_VIEWS = 'Video Third Quartile Views',
  VIDEO_UNMUTES = 'Video Unmutes',
  VIDEO_5_SEC_VIEWS = 'Video 5 Sec Views',
  VIEW_THROUGH_AD_ORDERS = 'View Through Ad Orders',
  VIEW_THROUGH_AD_UNITS = 'View Through Ad Units',
  INVENTORY = 'Inventory',
  AVAIL_TO_SELL_QUANTITY = 'Available To Sell Quantity',
  RETURNS = 'Returns',
  CANCELLED_ORDERS = 'Cancelled Orders',
  REFUND_ORDERS = 'Refund Orders',
  GROSS_UNITS_SOLD = 'Gross Units Sold',
  AD_UNITS_SOLD = 'Ad Units Sold',
  CAMPAIGNS = 'Campaigns',
  IN_STORE_UNITS_SOLD = 'In Store Units Sold',
  IN_STORE_ORDERS = 'In Store Orders',
  INPUT_QUANTITY = 'Input Quantity',

  PRODUCT_AD = 'Product Name',
  BIDDER_MAX_BID = 'Max Bid',
  BIDDER_MIN_BID = 'Min Bid',
  BIDDER_TROAS = 'Target ROAS',
  BIDDER_STATUS = 'Status',
  COST = 'Cost',
  AVG_CLICKS = 'Avg Clicks',
  AVG_CVR = 'Avg CVR',
  CVR_MEDIAN = 'CVR Median',
  THIRTY_PERCENT_OF_TROAS = '30% of TROAS',
  THIRTY_FIVE_PERCENT_OF_ASP = '35% of ASP',
  FBA_INVENTORY = 'FBA Inventory',
  WFS_INVENTORY = 'WFS Inventory',
  DAYS_OF_SUPPLY = 'Days of Supply',
  WEEKS_OF_SUPPLY = 'Weeks of Supply',
  ESTIMATED_EXCESS_QUANTITY = 'Estimated Excess Quantity',
  TOTAL_ORDERS = 'Total Orders',
  TOTAL_ACOS = 'Total ACOS',
  NET_PROFIT = 'Net Profit',
  INV_AGE_0_90 = 'Inventory Age 0–90',
  INV_AGE_91_180 = 'Inventory Age 91–180',
  INV_AGE_181_270 = 'Inventory Age 181–270',
  INV_AGE_271_365 = 'Inventory Age 271–365',
  INV_AGE_365_PLUS = 'Inventory Age 365+',
  TOTAL_AGED_INVENTORY = 'Total Aged Inventory',

  CAMPAIGN_BUDGET = 'Campaign Budget',
  OUT_OF_BUDGET = 'Out Of Budget',
  DAYS_SINCE_CAMPAIGN_START = 'Days Since Campaign Start',
  AVG_SPEND = 'Average Spend',
  CPA = 'Cost Per Acquisition',
  TACOS_TARGET = 'TACoS Target',
  OOB_PERCENTAGE = 'Out Of Budget Percentage',
  OUT_OF_BUDGET_HOUR = 'Out Of Budget Hour',

  TOS_IMPRESSIONS = 'Top Of Search Impressions',
  TOS_CLICKS = 'Top Of Search Clicks',
  TOS_UNITS_SOLD = 'Top Of Search Units Sold',
  TOS_CPC = 'Top Of Search Cost Per Click',
  TOS_CVR = 'Top Of Search Conversion Rate',
  TOS_CTR = 'Top Of Search Click Through Rate',
  TOS_SALES = 'Top Of Search Sales',
  TOS_SPEND = 'Top Of Search Spend',
  TOS_ACOS = 'Top Of Search Advertising Cost Of Sale',
  TOS_ROAS = 'Top Of Search Return On Ad Spend',

  ROS_IMPRESSIONS = 'Rest Of Search Impressions',
  ROS_CLICKS = 'Rest Of Search Clicks',
  ROS_UNITS_SOLD = 'Rest Of Search Units Sold',
  ROS_CPC = 'Rest Of Search Cost Per Click',
  ROS_CVR = 'Rest Of Search Conversion Rate',
  ROS_CTR = 'Rest Of Search Click Through Rate',
  ROS_SALES = 'Rest Of Search Sales',
  ROS_SPEND = 'Rest Of Search Spend',
  ROS_ACOS = 'Rest Of Search Advertising Cost Of Sale',
  ROS_ROAS = 'Rest Of Search Return On Ad Spend',

  PRODUCT_PAGE_IMPRESSIONS = 'Product Page Impressions',
  PRODUCT_PAGE_CLICKS = 'Product Page Clicks',
  PRODUCT_PAGE_UNITS_SOLD = 'Product Page Units Sold',
  PRODUCT_PAGE_CPC = 'Product Page Cost Per Click',
  PRODUCT_PAGE_CVR = 'Product Page Conversion Rate',
  PRODUCT_PAGE_CTR = 'Product Page Click Through Rate',
  PRODUCT_PAGE_SALES = 'Product Page Sales',
  PRODUCT_PAGE_SPEND = 'Product Page Spend',
  PRODUCT_PAGE_ACOS = 'Product Page Advertising Cost Of Sale',
  PRODUCT_PAGE_ROAS = 'Product Page Return On Ad Spend',

  BUY_BOX_IMPRESSIONS = 'Buy Box Impressions',
  BUY_BOX_CLICKS = 'Buy Box Clicks',
  BUY_BOX_UNITS_SOLD = 'Buy Box Units Sold',
  BUY_BOX_CPC = 'Buy Box Cost Per Click',
  BUY_BOX_CVR = 'Buy Box Conversion Rate',
  BUY_BOX_CTR = 'Buy Box Click Through Rate',
  BUY_BOX_SALES = 'Buy Box Sales',
  BUY_BOX_SPEND = 'Buy Box Spend',
  BUY_BOX_ACOS = 'Buy Box Advertising Cost Of Sale',
  BUY_BOX_ROAS = 'Buy Box Return On Ad Spend',

  SEARCH_INGRID_IMPRESSIONS = 'Search Ingrid Impressions',
  SEARCH_INGRID_CLICKS = 'Search Ingrid Clicks',
  SEARCH_INGRID_UNITS_SOLD = 'Search Ingrid Units Sold',
  SEARCH_INGRID_CPC = 'Search Ingrid Cost Per Click',
  SEARCH_INGRID_CVR = 'Search Ingrid Conversion Rate',
  SEARCH_INGRID_CTR = 'Search Ingrid Click Through Rate',
  SEARCH_INGRID_SALES = 'Search Ingrid Sales',
  SEARCH_INGRID_SPEND = 'Search Ingrid Spend',
  SEARCH_INGRID_ACOS = 'Search Ingrid Advertising Cost Of Sale',
  SEARCH_INGRID_ROAS = 'Search Ingrid Return On Ad Spend',

  HOME_PAGE_IMPRESSIONS = 'Home Page Impressions',
  HOME_PAGE_CLICKS = 'Home Page Clicks',
  HOME_PAGE_UNITS_SOLD = 'Home Page Units Sold',
  HOME_PAGE_CPC = 'Home Page Cost Per Click',
  HOME_PAGE_CVR = 'Home Page Conversion Rate',
  HOME_PAGE_CTR = 'Home Page Click Through Rate',
  HOME_PAGE_SALES = 'Home Page Sales',
  HOME_PAGE_SPEND = 'Home Page Spend',
  HOME_PAGE_ACOS = 'Home Page Advertising Cost Of Sale',
  HOME_PAGE_ROAS = 'Home Page Return On Ad Spend',

  STOCK_UP_IMPRESSIONS = 'Stock Up Impressions',
  STOCK_UP_CLICKS = 'Stock Up Clicks',
  STOCK_UP_UNITS_SOLD = 'Stock Up Units Sold',
  STOCK_UP_CPC = 'Stock Up Cost Per Click',
  STOCK_UP_CVR = 'Stock Up Conversion Rate',
  STOCK_UP_CTR = 'Stock Up Click Through Rate',
  STOCK_UP_SALES = 'Stock Up Sales',
  STOCK_UP_SPEND = 'Stock Up Spend',
  STOCK_UP_ACOS = 'Stock Up Advertising Cost Of Sale',
  STOCK_UP_ROAS = 'Stock Up Return On Ad Spend',

  STATISTICALLY_SIGNIFICANT_CLICKS = 'Statistically Significant Clicks',
  SELLER_FULFILLED_INVENTORY = 'Seller Fulfilled Inventory',
}

export enum AuditStatusEnum {
  IDLE = 'idle',
  PROCESSING = 'processing',
  SUCCESS = 'success',
  WARNING = 'warning',
}

export enum RuleEntityTableEnum {
  CAMPAIGN = 'Campaigns',
  AD_GROUP = 'Ad Groups',
  KEYWORD = 'Keyword',
  PRODUCT = 'Products',
}

export enum RulesSearchColumns {
  RULE_NAME = 'ruleName',
  RULE_ID = 'ruleId',
  RULE_TYPE = 'ruleType',
  NAME = 'name',
  ENTITY_ID = 'entityId',
}

export enum AppliedRulesColumnIds {
  RULE_NAME = 'Rule Name',
  RULE_TYPE = 'Rule Type',
  DATE_CREATED = 'Date Created',
  ENTITIES_COUNT = 'Linked Entities',
  RUN_BETWEEN = 'Run Between',
  FREQUENCY = 'Frequency',
  LAST_RUN = 'Last Run',
  STATUS_TOGGLE = 'Status Toggle',
  RULE_STATUS = 'Rule Status',
  NEXT_TRIGGER = 'Next Trigger',
}

export enum RuleDetailsTypeEnum {
  RULE = 'rule',
  TEMPLATE = 'template',
}

export enum RuleAdjustmentTypeEnum {
  PLATFORM = 'PLATFORM',
  PLACEMENT = 'PLACEMENT',
}

export type RulePlacementAdjustmentType =
  | PlacementBids.TOP_OF_SEARCH
  | PlacementBids.REST_OF_SEARCH
  | PlacementBids.PRODUCT_PAGES;

export type RulePlatformAdjustmentType =
  | FilterDropdownValue.DESKTOP
  | FilterDropdownValue.MOBILE
  | FilterDropdownValue.APP;

export type RulePageTypeAdjustmentType =
  | PageTypeActualEnum.ITEM
  | PageTypeActualEnum.SEARCH
  | PageTypeActualEnum.HOMEPAGE
  | PageTypeActualEnum.STOCK_UP;

export type RuleAdjustmentTargetType =
  | RulePlacementAdjustmentType
  | RulePlatformAdjustmentType
  | RulePageTypeAdjustmentType;

export type MetricValueConstraintType = MetricsKeysEnum | TRuleValueType;

export enum RulesPageTitleEnum {
  APPLIED_RULES = FeaturesEnum.APPLIED_RULES,
}
