import { CampaignStateEnum, RuleAutomationStatusEnum } from '@/enums/advertising.enums';
import {
  ICampaign,
  IPerformanceGraphData,
} from '@/interfaces/advertising/amazon/sp-advertising.interface';
import { IPerformanceMetrics } from '@/interfaces/advertising/amazon/sp-advertising.interface';

export const MOCK_CAMPAIGNS: ICampaign[] = [
  {
    id: '1',
    _id: 'mock-id-1',
    campaignId: 1001,
    campaignName: 'Guvera - Auto - Brand Defense',
    status: CampaignStateEnum.ENABLED,
    adType: 'sp',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    targetingType: 'AUTO',
    budget: { budget: 250, budgetType: 'daily' },
    dynamicBidding: { strategy: 'Dynamic bids - down only', placementBidding: [] },
    profileId: 'mock-profile',
    impressions: 145230,
    clicks: 3420,
    adSpend: 4850.75,
    cpc: 1.42,
    ctr: 2.35,
    cvr: 8.2,
    unitsSold: 280,
    adSales: 18940.5,
    acos: 25.6,
    roas: 3.9,
    message: [],
    tagId: null,
    tagName: null,
    automationStatus: RuleAutomationStatusEnum.ENABLED,
  },
  {
    id: '2',
    _id: 'mock-id-2',
    campaignId: 1002,
    campaignName: 'SP - Exact - Top Keywords',
    status: CampaignStateEnum.ENABLED,
    adType: 'sp',
    startDate: '2026-06-15',
    endDate: '2026-08-31',
    targetingType: 'MANUAL',
    budget: { budget: 500, budgetType: 'daily' },
    dynamicBidding: { strategy: 'Dynamic bids - up and down', placementBidding: [] },
    profileId: 'mock-profile',
    impressions: 289400,
    clicks: 7850,
    adSpend: 12430.2,
    cpc: 1.58,
    ctr: 2.71,
    cvr: 6.5,
    unitsSold: 510,
    adSales: 42800.0,
    acos: 29.0,
    roas: 3.44,
    message: [],
    tagId: 'tag-sp',
    tagName: 'SP',
    automationStatus: null,
  },
  {
    id: '3',
    _id: 'mock-id-3',
    campaignId: 1003,
    campaignName: 'Auto - Product Targeting - Competitors',
    status: CampaignStateEnum.PAUSED,
    adType: 'sp',
    startDate: '2026-05-01',
    endDate: '2026-07-31',
    targetingType: 'AUTO',
    budget: { budget: 150, budgetType: 'daily' },
    dynamicBidding: { strategy: 'Fixed bids', placementBidding: [] },
    profileId: 'mock-profile',
    impressions: 67800,
    clicks: 1540,
    adSpend: 2180.3,
    cpc: 1.42,
    ctr: 2.27,
    cvr: 5.8,
    unitsSold: 89,
    adSales: 7200.0,
    acos: 30.3,
    roas: 3.3,
    message: [],
    tagId: null,
    tagName: null,
    automationStatus: RuleAutomationStatusEnum.PAUSED,
  },
  {
    id: '4',
    _id: 'mock-id-4',
    campaignId: 1004,
    campaignName: 'Guvera - Broad - Category Terms',
    status: CampaignStateEnum.ENABLED,
    adType: 'sp',
    startDate: '2026-07-10',
    endDate: '2026-10-15',
    targetingType: 'MANUAL',
    budget: { budget: 350, budgetType: 'daily' },
    dynamicBidding: { strategy: 'Dynamic bids - down only', placementBidding: [] },
    profileId: 'mock-profile',
    impressions: 198500,
    clicks: 5120,
    adSpend: 7680.45,
    cpc: 1.5,
    ctr: 2.58,
    cvr: 7.1,
    unitsSold: 364,
    adSales: 28500.0,
    acos: 27.0,
    roas: 3.71,
    message: [],
    tagId: 'tag-auto',
    tagName: 'Auto',
    automationStatus: RuleAutomationStatusEnum.ENABLED,
  },
  {
    id: '5',
    _id: 'mock-id-5',
    campaignId: 1005,
    campaignName: 'SP - ASIN Targeting - Own Products',
    status: CampaignStateEnum.ENABLED,
    adType: 'sp',
    startDate: '2026-06-01',
    endDate: '2026-09-30',
    targetingType: 'MANUAL',
    budget: { budget: 200, budgetType: 'daily' },
    dynamicBidding: { strategy: 'Dynamic bids - down only', placementBidding: [] },
    profileId: 'mock-profile',
    impressions: 89200,
    clicks: 2340,
    adSpend: 3450.6,
    cpc: 1.47,
    ctr: 2.62,
    cvr: 9.4,
    unitsSold: 220,
    adSales: 15600.0,
    acos: 22.1,
    roas: 4.52,
    message: [],
    tagId: null,
    tagName: null,
    automationStatus: null,
  },
];

function createGraphPoint(
  label: string,
  impressions: number,
  clicks: number,
  adSpend: number,
  adSales: number,
  unitsSold: number
): IPerformanceGraphData {
  return {
    label,
    impressions,
    clicks,
    adSpend,
    cpc: clicks > 0 ? adSpend / clicks : 0,
    ctr: impressions > 0 ? (clicks / impressions) * 100 : 0,
    cvr: clicks > 0 ? (unitsSold / clicks) * 100 : 0,
    unitsSold,
    adSales,
    acos: adSales > 0 ? (adSpend / adSales) * 100 : 0,
    roas: adSpend > 0 ? adSales / adSpend : 0,
    products: 46,
    totalSales: adSales,
    totalUnits: unitsSold,
    tacos: adSales > 0 ? (adSpend / adSales) * 100 : 0,
    gmv: adSales,
    grossUnits: unitsSold,
    // Walmart fields
    adUnits: null,
    adOrders: null,
    advertisedSkuSales: null,
    otherSkuSales: null,
    advertisedSkuUnits: null,
    otherSkuUnits: null,
    ntbUnits: null,
    ntbOrders: null,
    ntbSales: null,
    cvrUnitsSoldBased: null,
    cvrOrdersSoldBased: null,
    percentNtbUnits: null,
    percentNtbOrders: null,
    percentNtbSales: null,
    inStoreAttributedSales: null,
    inStoreAdvertisedSales: null,
    inStoreOtherSales: null,
    inStoreUnitsSold: null,
    inStoreOrders: null,
    omniChannelSales: null,
    omniChannelRoas: null,
    completeViewOrders: null,
    completeViewAdUnits: null,
    videoCompleteViews: null,
    videoFirstQuartileViews: null,
    videoImpressions: null,
    videoMidpointViews: null,
    videoThirdQuartileViews: null,
    videoUnmutes: null,
    video5SecondViews: null,
    viewableImpressions: null,
    viewThroughAdOrders: null,
    viewThroughAdSales: null,
    viewThroughAdUnits: null,
    completeViewAdSales: null,
    otherCompleteViewAdSales: null,
    vtr: null,
    vctr: null,
    video5SecondViewRate: null,
  };
}

export const MOCK_GRAPH_DATA: IPerformanceGraphData[] = [
  createGraphPoint('Sep 02', 18500, 420, 620.5, 3200, 34),
  createGraphPoint('Sep 03', 21200, 510, 745.0, 3800, 41),
  createGraphPoint('Sep 04', 19800, 460, 680.3, 3500, 37),
  createGraphPoint('Sep 05', 23400, 580, 830.0, 4200, 48),
  createGraphPoint('Sep 06', 25100, 620, 895.75, 4600, 52),
  createGraphPoint('Sep 07', 22800, 540, 790.2, 4000, 44),
  createGraphPoint('Sep 08', 26500, 650, 920.0, 4800, 55),
];

export const MOCK_METRICS_DATA: IPerformanceMetrics = {
  currPerformanceData: {
    impressions: 820400,
    clicks: 21230,
    adSpend: 35280.5,
    cpc: 1.66,
    ctr: 2.59,
    cvr: 7.3,
    unitsSold: 1550,
    adSales: 128400.0,
    acos: 27.5,
    roas: 3.64,
    adUnits: null,
    adOrders: null,
    advertisedSkuSales: null,
    otherSkuSales: null,
    advertisedSkuUnits: null,
    otherSkuUnits: null,
    ntbUnits: null,
    ntbOrders: null,
    ntbSales: null,
    cvrUnitsSoldBased: null,
    cvrOrdersSoldBased: null,
    percentNtbUnits: null,
    percentNtbOrders: null,
    percentNtbSales: null,
    inStoreAttributedSales: null,
    inStoreAdvertisedSales: null,
    inStoreOtherSales: null,
    inStoreUnitsSold: null,
    inStoreOrders: null,
    omniChannelSales: null,
    omniChannelRoas: null,
    completeViewOrders: null,
    completeViewAdUnits: null,
    videoCompleteViews: null,
    videoFirstQuartileViews: null,
    videoImpressions: null,
    videoMidpointViews: null,
    videoThirdQuartileViews: null,
    videoUnmutes: null,
    video5SecondViews: null,
    viewableImpressions: null,
    viewThroughAdOrders: null,
    viewThroughAdSales: null,
    viewThroughAdUnits: null,
    completeViewAdSales: null,
    otherCompleteViewAdSales: null,
    vtr: null,
    vctr: null,
    video5SecondViewRate: null,
    totalSales: 128400.0,
    totalUnits: 1550,
    tacos: 27.5,
    gmv: 128400.0,
    grossUnits: 1550,
  },
  prevPerformanceData: {
    prevData: {
      impressions: 615000,
      clicks: 15800,
      adSpend: 26400.0,
      cpc: 1.67,
      ctr: 2.57,
      cvr: 6.9,
      unitsSold: 1090,
      adSales: 96200.0,
      acos: 27.4,
      roas: 3.64,
      adUnits: null,
      adOrders: null,
      advertisedSkuSales: null,
      otherSkuSales: null,
      advertisedSkuUnits: null,
      otherSkuUnits: null,
      ntbUnits: null,
      ntbOrders: null,
      ntbSales: null,
      cvrUnitsSoldBased: null,
      cvrOrdersSoldBased: null,
      percentNtbUnits: null,
      percentNtbOrders: null,
      percentNtbSales: null,
      inStoreAttributedSales: null,
      inStoreAdvertisedSales: null,
      inStoreOtherSales: null,
      inStoreUnitsSold: null,
      inStoreOrders: null,
      omniChannelSales: null,
      omniChannelRoas: null,
      completeViewOrders: null,
      completeViewAdUnits: null,
      videoCompleteViews: null,
      videoFirstQuartileViews: null,
      videoImpressions: null,
      videoMidpointViews: null,
      videoThirdQuartileViews: null,
      videoUnmutes: null,
      video5SecondViews: null,
      viewableImpressions: null,
      viewThroughAdOrders: null,
      viewThroughAdSales: null,
      viewThroughAdUnits: null,
      completeViewAdSales: null,
      otherCompleteViewAdSales: null,
      vtr: null,
      vctr: null,
      video5SecondViewRate: null,
      totalSales: 96200.0,
      totalUnits: 1090,
      tacos: 27.4,
      gmv: 96200.0,
      grossUnits: 1090,
    },
    prevText: 'Previous 7 days',
  },
};
